name: Docker Verification

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: ["*"]

jobs:
    docker-test:
        name: Docker Build and Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Build Docker image
              run: docker build -t product-insights-dashboard .

            - name: Test Docker container
              run: |
                  docker run -d --name test-container -p 8080:3000 product-insights-dashboard
                  sleep 10
                  curl -f http://localhost:8080/api/products/insights || exit 1
                  docker stop test-container
                  docker rm test-container
